import type { StorefrontPage } from "@ecommerce/shared";

// Default content used only when no CMS row exists yet for a given page key.
// Admin/CMS content always wins. Update these as your policies evolve.

export const termsAndConditionsDefault: StorefrontPage = {
  key: "terms_and_conditions",
  title: "Terms and Conditions",
  isActive: true,
  sortOrder: 100,
  localizedTitle: {
    en: "Terms and Conditions",
    zh: "条款与条件",
    ms: "Terma dan Syarat",
  },
  content: [
    "By placing an order at Urbanix Store, you agree to the following terms.",
    "",
    "- Orders are confirmed only after payment receipt is verified by our team.",
    "- Product images are for reference; actual colors may vary slightly.",
    "- Prices, promotions, and stock are subject to change without prior notice.",
    "- We reserve the right to cancel and refund any order with suspected fraud or pricing errors.",
    "- All disputes are governed by the laws of Malaysia.",
    "",
    "For any question, contact us via WhatsApp or email.",
  ].join("\n"),
  localizedContent: {
    en: [
      "By placing an order at Urbanix Store, you agree to the following terms.",
      "",
      "- Orders are confirmed only after payment receipt is verified by our team.",
      "- Product images are for reference; actual colors may vary slightly.",
      "- Prices, promotions, and stock are subject to change without prior notice.",
      "- We reserve the right to cancel and refund any order with suspected fraud or pricing errors.",
      "- All disputes are governed by the laws of Malaysia.",
      "",
      "For any question, contact us via WhatsApp or email.",
    ].join("\n"),
    zh: [
      "在 Urbanix Store 下单即表示您同意以下条款。",
      "",
      "- 订单需在我们的团队核实付款凭证后才会确认。",
      "- 产品图片仅供参考，实物颜色可能略有不同。",
      "- 价格、促销与库存如有更改，恕不另行通知。",
      "- 如发现欺诈或价格错误，我们保留取消并退款的权利。",
      "- 所有争议均受马来西亚法律管辖。",
      "",
      "如有任何疑问，请通过 WhatsApp 或电邮联系我们。",
    ].join("\n"),
    ms: [
      "Dengan membuat pesanan di Urbanix Store, anda bersetuju dengan terma berikut.",
      "",
      "- Pesanan disahkan hanya selepas resit pembayaran disahkan oleh pasukan kami.",
      "- Gambar produk adalah untuk rujukan; warna sebenar mungkin berbeza sedikit.",
      "- Harga, promosi dan stok boleh berubah tanpa notis terlebih dahulu.",
      "- Kami berhak membatalkan dan memulangkan wang bagi mana-mana pesanan yang disyaki penipuan atau ralat harga.",
      "- Semua pertikaian tertakluk kepada undang-undang Malaysia.",
      "",
      "Untuk sebarang pertanyaan, hubungi kami melalui WhatsApp atau e-mel.",
    ].join("\n"),
  },
};

export const refundPolicyDefault: StorefrontPage = {
  key: "refund_policy",
  title: "Refund Policy",
  isActive: true,
  sortOrder: 101,
  localizedTitle: {
    en: "Refund Policy",
    zh: "退款政策",
    ms: "Polisi Bayaran Balik",
  },
  content: [
    "We want every customer to be confident shopping with Urbanix Store.",
    "",
    "- Refunds are issued for orders that cannot be fulfilled or are confirmed as defective on arrival.",
    "- Refund requests must be raised within 7 days of delivery via WhatsApp or email, with order number and clear photos/video.",
    "- Approved refunds are processed within 3–7 working days to your original bank account.",
    "- Shipping fees are non-refundable unless the issue is caused by us.",
    "- Items damaged through customer misuse are not eligible for refund.",
  ].join("\n"),
  localizedContent: {
    en: [
      "We want every customer to be confident shopping with Urbanix Store.",
      "",
      "- Refunds are issued for orders that cannot be fulfilled or are confirmed as defective on arrival.",
      "- Refund requests must be raised within 7 days of delivery via WhatsApp or email, with order number and clear photos/video.",
      "- Approved refunds are processed within 3–7 working days to your original bank account.",
      "- Shipping fees are non-refundable unless the issue is caused by us.",
      "- Items damaged through customer misuse are not eligible for refund.",
    ].join("\n"),
    zh: [
      "我们希望每位顾客都能放心在 Urbanix Store 购物。",
      "",
      "- 若订单无法履行或商品到货时确认有瑕疵，我们将提供退款。",
      "- 退款申请须在收到商品后 7 天内透过 WhatsApp 或电邮提出，并附上订单编号与清晰的照片/视频。",
      "- 经核准的退款将在 3–7 个工作日内退回您原本付款的银行账户。",
      "- 除非问题由我方造成，运费一律不退。",
      "- 因客户使用不当造成的损坏不在退款范围内。",
    ].join("\n"),
    ms: [
      "Kami mahu setiap pelanggan yakin membeli-belah di Urbanix Store.",
      "",
      "- Bayaran balik diberikan untuk pesanan yang tidak dapat dipenuhi atau disahkan rosak semasa diterima.",
      "- Permohonan bayaran balik mesti dibuat dalam tempoh 7 hari selepas penghantaran melalui WhatsApp atau e-mel, beserta nombor pesanan dan gambar/video jelas.",
      "- Bayaran balik yang diluluskan akan diproses dalam 3–7 hari bekerja ke akaun bank asal anda.",
      "- Yuran penghantaran tidak dikembalikan kecuali masalah disebabkan oleh kami.",
      "- Barang yang rosak akibat salah guna pelanggan tidak layak untuk bayaran balik.",
    ].join("\n"),
  },
};

export const returnPolicyDefault: StorefrontPage = {
  key: "return_policy",
  title: "Return Policy",
  isActive: true,
  sortOrder: 102,
  localizedTitle: {
    en: "Return Policy",
    zh: "退换货政策",
    ms: "Polisi Pemulangan",
  },
  content: [
    "Returns are accepted for damaged, defective, or wrong items.",
    "",
    "- Notify us within 7 days of delivery with order number, photos and a short video of the issue.",
    "- Items must be returned in original packaging with all accessories.",
    "- Return shipping is covered by us if the fault is ours; otherwise covered by the customer.",
    "- Once received and inspected, we will either replace the item or issue a refund based on stock availability.",
    "- Hygiene-sensitive items and used items are not returnable.",
  ].join("\n"),
  localizedContent: {
    en: [
      "Returns are accepted for damaged, defective, or wrong items.",
      "",
      "- Notify us within 7 days of delivery with order number, photos and a short video of the issue.",
      "- Items must be returned in original packaging with all accessories.",
      "- Return shipping is covered by us if the fault is ours; otherwise covered by the customer.",
      "- Once received and inspected, we will either replace the item or issue a refund based on stock availability.",
      "- Hygiene-sensitive items and used items are not returnable.",
    ].join("\n"),
    zh: [
      "我们接受损坏、有瑕疵或错发商品的退换货。",
      "",
      "- 请在收到商品 7 天内通知我们，并提供订单编号、问题的照片与短视频。",
      "- 商品须以原包装连同所有配件寄回。",
      "- 若属我方过失，退货运费由我方承担；否则由客户承担。",
      "- 收到并检查后，我们将根据库存情况安排换货或退款。",
      "- 涉及卫生的商品及已使用的商品不予退换。",
    ].join("\n"),
    ms: [
      "Pemulangan diterima untuk item rosak, cacat atau salah hantar.",
      "",
      "- Maklumkan kepada kami dalam 7 hari selepas penghantaran dengan nombor pesanan, gambar dan video pendek mengenai masalah tersebut.",
      "- Item mesti dipulangkan dalam pembungkusan asal beserta semua aksesori.",
      "- Kos penghantaran balik ditanggung oleh kami jika kesilapan dari pihak kami; jika tidak, ditanggung oleh pelanggan.",
      "- Selepas diterima dan diperiksa, kami akan menggantikan item atau memulangkan wang berdasarkan stok yang ada.",
      "- Item sensitif kebersihan dan item yang telah digunakan tidak boleh dipulangkan.",
    ].join("\n"),
  },
};

export const faqDefault: StorefrontPage = {
  key: "faq",
  title: "Frequently Asked Questions",
  isActive: true,
  sortOrder: 103,
  localizedTitle: {
    en: "Frequently Asked Questions",
    zh: "常见问题",
    ms: "Soalan Lazim",
  },
  content: [
    "How long is delivery?",
    "West Malaysia 2–4 working days, East Malaysia 4–7 working days after payment verification.",
    "",
    "How do I pay?",
    "Scan the Bank QR code at checkout and upload your payment receipt. Orders are confirmed after our team verifies the payment.",
    "",
    "Do you offer free shipping?",
    "Yes. Free shipping for West Malaysia orders above RM80 and East Malaysia (including Labuan) orders above RM150.",
    "",
    "How do I track my order?",
    "Use the Track Order page with your order number and the phone number you used at checkout.",
    "",
    "Can I cancel or change my order?",
    "Contact us via WhatsApp as soon as possible. Once the parcel is shipped we cannot make changes.",
  ].join("\n"),
  localizedContent: {
    en: [
      "How long is delivery?",
      "West Malaysia 2–4 working days, East Malaysia 4–7 working days after payment verification.",
      "",
      "How do I pay?",
      "Scan the Bank QR code at checkout and upload your payment receipt. Orders are confirmed after our team verifies the payment.",
      "",
      "Do you offer free shipping?",
      "Yes. Free shipping for West Malaysia orders above RM80 and East Malaysia (including Labuan) orders above RM150.",
      "",
      "How do I track my order?",
      "Use the Track Order page with your order number and the phone number you used at checkout.",
      "",
      "Can I cancel or change my order?",
      "Contact us via WhatsApp as soon as possible. Once the parcel is shipped we cannot make changes.",
    ].join("\n"),
    zh: [
      "送货需要多久？",
      "付款核实后，西马 2–4 个工作日，东马 4–7 个工作日。",
      "",
      "如何付款？",
      "结账时扫描银行 QR 码并上传付款凭证。我们核实付款后订单即确认。",
      "",
      "有免运费吗？",
      "有。西马订单满 RM80、东马（含纳闽）订单满 RM150 即享免运费。",
      "",
      "如何追踪订单？",
      "在「追踪订单」页面输入订单编号与结账时使用的电话号码即可。",
      "",
      "可以取消或修改订单吗？",
      "请尽快通过 WhatsApp 联系我们。包裹一经寄出，便无法更改。",
    ].join("\n"),
    ms: [
      "Berapa lama penghantaran?",
      "Semenanjung Malaysia 2–4 hari bekerja, Malaysia Timur 4–7 hari bekerja selepas pembayaran disahkan.",
      "",
      "Bagaimana cara membayar?",
      "Imbas kod QR Bank semasa pembayaran dan muat naik resit anda. Pesanan disahkan selepas pasukan kami mengesahkan pembayaran.",
      "",
      "Adakah anda menawarkan penghantaran percuma?",
      "Ya. Penghantaran percuma untuk Semenanjung Malaysia melebihi RM80 dan Malaysia Timur (termasuk Labuan) melebihi RM150.",
      "",
      "Bagaimana untuk menjejak pesanan?",
      "Gunakan halaman Jejak Pesanan dengan nombor pesanan dan nombor telefon yang digunakan semasa pembayaran.",
      "",
      "Bolehkah saya membatalkan atau menukar pesanan?",
      "Hubungi kami melalui WhatsApp secepat mungkin. Setelah bungkusan dihantar, kami tidak dapat membuat sebarang perubahan.",
    ].join("\n"),
  },
};
