import type { StorefrontPage } from "@ecommerce/shared";

// Default content used only when no CMS row exists yet for a given page key.
// Admin/CMS content always wins. Update these as your policies evolve.
//
// Phase 2A launch-ready content: EN / 中文 / BM verified copy suitable for
// soft launch. PDPA Act 709 section is included on the Privacy Policy.

export const shippingDefault: StorefrontPage = {
  key: "shipping",
  title: "Shipping & Delivery",
  isActive: true,
  sortOrder: 10,
  localizedTitle: {
    en: "Shipping & Delivery",
    zh: "运送与配送",
    ms: "Penghantaran",
  },
  content: [
    "We ship across Malaysia with trusted couriers.",
    "",
    "**Delivery time**",
    "- West Malaysia: 2–4 working days after payment is verified.",
    "- East Malaysia (Sabah, Sarawak, Labuan): 4–7 working days after payment is verified.",
    "",
    "**Free shipping**",
    "- West Malaysia orders above RM80.",
    "- East Malaysia and Labuan orders above RM150.",
    "",
    "**Couriers we use**",
    "- J&T Express, Ninja Van, Pos Laju.",
    "",
    "**Cut-off and working days**",
    "- Orders verified before 2 pm Mon–Fri are packed the same day.",
    "- We do not ship on Saturdays, Sundays, or Malaysia public holidays. Orders placed on these days are processed on the next working day.",
    "",
    "**Tracking**",
    "- A tracking number is sent via WhatsApp once the parcel is collected by the courier (usually within 24 hours of dispatch).",
    "- You can also use the Track Order page with your order number and phone number.",
  ].join("\n"),
  localizedContent: {
    en: [
      "We ship across Malaysia with trusted couriers.",
      "",
      "**Delivery time**",
      "- West Malaysia: 2–4 working days after payment is verified.",
      "- East Malaysia (Sabah, Sarawak, Labuan): 4–7 working days after payment is verified.",
      "",
      "**Free shipping**",
      "- West Malaysia orders above RM80.",
      "- East Malaysia and Labuan orders above RM150.",
      "",
      "**Couriers we use**",
      "- J&T Express, Ninja Van, Pos Laju.",
      "",
      "**Cut-off and working days**",
      "- Orders verified before 2 pm Mon–Fri are packed the same day.",
      "- We do not ship on Saturdays, Sundays, or Malaysia public holidays. Orders placed on these days are processed on the next working day.",
      "",
      "**Tracking**",
      "- A tracking number is sent via WhatsApp once the parcel is collected by the courier (usually within 24 hours of dispatch).",
      "- You can also use the Track Order page with your order number and phone number.",
    ].join("\n"),
    zh: [
      "我们透过可靠的快递服务寄送至全马。",
      "",
      "**配送时间**",
      "- 西马：付款核实后 2–4 个工作日送达。",
      "- 东马（沙巴、砂拉越、纳闽）：付款核实后 4–7 个工作日送达。",
      "",
      "**免邮门槛**",
      "- 西马订单满 RM80。",
      "- 东马及纳闽订单满 RM150。",
      "",
      "**合作快递**",
      "- J&T Express、Ninja Van、Pos Laju。",
      "",
      "**截单与工作日**",
      "- 周一至周五下午 2 点前核实付款的订单当天打包。",
      "- 我们周六、周日及马来西亚公共假期不发货，订单将顺延至下一个工作日处理。",
      "",
      "**追踪**",
      "- 包裹由快递员收取后（通常 24 小时内），追踪号码将通过 WhatsApp 发送给您。",
      "- 您也可以在「追踪订单」页面输入订单编号与电话号码查询。",
    ].join("\n"),
    ms: [
      "Kami menghantar ke seluruh Malaysia dengan kurier yang dipercayai.",
      "",
      "**Masa penghantaran**",
      "- Semenanjung Malaysia: 2–4 hari bekerja selepas pembayaran disahkan.",
      "- Malaysia Timur (Sabah, Sarawak, Labuan): 4–7 hari bekerja selepas pembayaran disahkan.",
      "",
      "**Penghantaran percuma**",
      "- Pesanan Semenanjung Malaysia melebihi RM80.",
      "- Pesanan Malaysia Timur dan Labuan melebihi RM150.",
      "",
      "**Kurier rakan kongsi**",
      "- J&T Express, Ninja Van, Pos Laju.",
      "",
      "**Masa potong dan hari bekerja**",
      "- Pesanan yang disahkan sebelum 2 petang Isnin–Jumaat akan dibungkus pada hari yang sama.",
      "- Kami tidak menghantar pada Sabtu, Ahad atau cuti umum Malaysia. Pesanan pada hari tersebut akan diproses pada hari bekerja berikutnya.",
      "",
      "**Penjejakan**",
      "- Nombor penjejakan dihantar melalui WhatsApp sebaik sahaja bungkusan dikutip oleh kurier (biasanya dalam 24 jam selepas penghantaran).",
      "- Anda juga boleh guna halaman Jejak Pesanan dengan nombor pesanan dan nombor telefon.",
    ].join("\n"),
  },
};

export const contactUsDefault: StorefrontPage = {
  key: "contact_us",
  title: "Contact Us",
  isActive: true,
  sortOrder: 20,
  localizedTitle: {
    en: "Contact Us",
    zh: "联系我们",
    ms: "Hubungi Kami",
  },
  content: [
    "We are here to help.",
    "",
    "- WhatsApp is the fastest way to reach our team. The number is shown in the footer of every page.",
    "- We reply during business hours (Mon–Sat, 9 am–9 pm), typically within a few hours.",
    "- For order issues, please include your order number and a short description so we can help faster.",
    "- For damaged or wrong items, attach clear photos within 24 hours of delivery.",
    "",
    "You can also email us using the address listed in the footer.",
  ].join("\n"),
  localizedContent: {
    en: [
      "We are here to help.",
      "",
      "- WhatsApp is the fastest way to reach our team. The number is shown in the footer of every page.",
      "- We reply during business hours (Mon–Sat, 9 am–9 pm), typically within a few hours.",
      "- For order issues, please include your order number and a short description so we can help faster.",
      "- For damaged or wrong items, attach clear photos within 24 hours of delivery.",
      "",
      "You can also email us using the address listed in the footer.",
    ].join("\n"),
    zh: [
      "我们随时为您服务。",
      "",
      "- WhatsApp 是联系我们最快的方式，号码显示在每一页的页脚。",
      "- 我们的工作时间为周一至周六上午 9 时至晚上 9 时，通常数小时内回复。",
      "- 如有订单问题，请附上订单编号及简短说明，以便我们更快协助。",
      "- 若收到损坏或错送商品，请于收货 24 小时内附上清晰照片。",
      "",
      "您也可以使用页脚显示的电邮地址与我们联系。",
    ].join("\n"),
    ms: [
      "Kami sedia membantu.",
      "",
      "- WhatsApp adalah cara terpantas untuk menghubungi kami. Nombor dipaparkan di footer setiap halaman.",
      "- Kami membalas dalam waktu bekerja (Isnin–Sabtu, 9 pagi–9 malam), biasanya dalam beberapa jam.",
      "- Untuk isu pesanan, sila sertakan nombor pesanan dan keterangan ringkas supaya kami dapat membantu dengan lebih pantas.",
      "- Untuk barang rosak atau salah hantar, sila lampirkan gambar jelas dalam 24 jam selepas penerimaan.",
      "",
      "Anda juga boleh menghubungi kami melalui e-mel yang disenaraikan di footer.",
    ].join("\n"),
  },
};

export const ourStoryDefault: StorefrontPage = {
  key: "our_story",
  title: "Our Story",
  isActive: true,
  sortOrder: 30,
  localizedTitle: {
    en: "Our Story",
    zh: "我们的故事",
    ms: "Kisah Kami",
  },
  content: [
    "Urbanix Store curates practical lifestyle essentials for everyday urban living in Malaysia.",
    "",
    "We focus on small wins: products that are well-made, fairly priced, and useful from the first day.",
    "",
    "Every order is packed and checked by a small team that cares about getting the details right. We ship from Selangor and reply on WhatsApp during business hours.",
  ].join("\n"),
  localizedContent: {
    en: [
      "Urbanix Store curates practical lifestyle essentials for everyday urban living in Malaysia.",
      "",
      "We focus on small wins: products that are well-made, fairly priced, and useful from the first day.",
      "",
      "Every order is packed and checked by a small team that cares about getting the details right. We ship from Selangor and reply on WhatsApp during business hours.",
    ].join("\n"),
    zh: [
      "Urbanix Store 精选实用的生活必需品，陪伴马来西亚都市人的日常。",
      "",
      "我们追求的是「小确幸」：用料扎实、价格合理、即刻好用的产品。",
      "",
      "每一份订单都由用心的小团队亲手包装与核对。我们从雪兰莪发货，并于工作时间内透过 WhatsApp 回复您。",
    ].join("\n"),
    ms: [
      "Urbanix Store memilih barangan keperluan gaya hidup yang praktikal untuk kehidupan bandar di Malaysia.",
      "",
      "Kami fokus pada perkara kecil yang berkualiti: produk yang elok dibuat, berharga berpatutan, dan berguna dari hari pertama.",
      "",
      "Setiap pesanan dibungkus dan disemak oleh pasukan kecil yang mengambil berat tentang setiap butiran. Kami menghantar dari Selangor dan membalas WhatsApp pada waktu bekerja.",
    ].join("\n"),
  },
};

export const privacyPolicyDefault: StorefrontPage = {
  key: "privacy_policy",
  title: "Privacy Policy",
  isActive: true,
  sortOrder: 40,
  localizedTitle: {
    en: "Privacy Policy",
    zh: "隐私政策",
    ms: "Polisi Privasi",
  },
  content: [
    "Your privacy matters to us.",
    "",
    "- We collect only the information needed to process your order: name, phone number, address, and (optionally) email.",
    "- Payment receipts you upload are stored securely and used only to verify your payment.",
    "- We do not sell your personal information to third parties.",
    "- We share order details with couriers strictly to deliver your parcel.",
    "- You may request deletion of your customer profile by contacting us via WhatsApp or email.",
    "",
    "**PDPA Compliance (Malaysia)**",
    "",
    "This store complies with the Malaysia Personal Data Protection Act 2010 (Act 709).",
    "",
    "- We collect, use, and store your personal data only for processing your order, fulfilling delivery, and providing customer support.",
    "- Personal data we handle: name, phone number, delivery address, optional email, and payment receipt images.",
    "- We do not transfer your personal data outside Malaysia except to courier partners required to deliver your parcel.",
    "- You have the right to access, correct, or request deletion of your personal data at any time by contacting us using the details on the Contact Us page.",
    "- We retain order records for up to 7 years for accounting and tax purposes, as commonly required by Malaysian law.",
    "",
    "This policy may be updated from time to time. The latest version always applies.",
  ].join("\n"),
  localizedContent: {
    en: [
      "Your privacy matters to us.",
      "",
      "- We collect only the information needed to process your order: name, phone number, address, and (optionally) email.",
      "- Payment receipts you upload are stored securely and used only to verify your payment.",
      "- We do not sell your personal information to third parties.",
      "- We share order details with couriers strictly to deliver your parcel.",
      "- You may request deletion of your customer profile by contacting us via WhatsApp or email.",
      "",
      "**PDPA Compliance (Malaysia)**",
      "",
      "This store complies with the Malaysia Personal Data Protection Act 2010 (Act 709).",
      "",
      "- We collect, use, and store your personal data only for processing your order, fulfilling delivery, and providing customer support.",
      "- Personal data we handle: name, phone number, delivery address, optional email, and payment receipt images.",
      "- We do not transfer your personal data outside Malaysia except to courier partners required to deliver your parcel.",
      "- You have the right to access, correct, or request deletion of your personal data at any time by contacting us using the details on the Contact Us page.",
      "- We retain order records for up to 7 years for accounting and tax purposes, as commonly required by Malaysian law.",
      "",
      "This policy may be updated from time to time. The latest version always applies.",
    ].join("\n"),
    zh: [
      "我们重视您的隐私。",
      "",
      "- 我们只收集处理订单所需的资料：姓名、电话、地址，以及（可选）电邮。",
      "- 您上传的付款凭证将被安全存储，仅用于核实付款。",
      "- 我们不会将您的个人资料出售给第三方。",
      "- 我们仅将订单资料分享给快递公司以完成派送。",
      "- 您可透过 WhatsApp 或电邮联系我们，要求删除您的客户资料。",
      "",
      "**个人资料保护法令 (PDPA) 合规**",
      "",
      "本店遵守马来西亚《2010 年个人资料保护法令》(Act 709)。",
      "",
      "- 我们仅为处理订单、完成配送及提供客户支持的目的收集、使用及保存您的个人资料。",
      "- 我们处理的个人资料包括：姓名、电话号码、收货地址、（可选）电邮、以及付款收据图片。",
      "- 除运送包裹所需的快递合作伙伴外，我们不会将您的个人资料转移至马来西亚境外。",
      "- 您随时有权要求查阅、更正或删除您的个人资料。请通过「联系我们」页面提供的资料与我们联系。",
      "- 依据马来西亚相关法律一般要求，我们将订单记录保留最长 7 年以供会计及税务用途。",
      "",
      "本政策可能不时更新，最新版本即为有效版本。",
    ].join("\n"),
    ms: [
      "Privasi anda penting bagi kami.",
      "",
      "- Kami hanya mengumpul maklumat yang diperlukan untuk memproses pesanan: nama, nombor telefon, alamat, dan (pilihan) e-mel.",
      "- Resit pembayaran yang anda muat naik disimpan dengan selamat dan digunakan hanya untuk pengesahan pembayaran.",
      "- Kami tidak menjual maklumat peribadi anda kepada pihak ketiga.",
      "- Kami berkongsi maklumat pesanan dengan kurier semata-mata untuk menghantar bungkusan anda.",
      "- Anda boleh meminta pemadaman profil pelanggan dengan menghubungi kami melalui WhatsApp atau e-mel.",
      "",
      "**Kepatuhan Akta Perlindungan Data Peribadi (PDPA)**",
      "",
      "Kedai ini mematuhi Akta Perlindungan Data Peribadi Malaysia 2010 (Akta 709).",
      "",
      "- Kami mengumpul, menggunakan, dan menyimpan data peribadi anda hanya untuk memproses pesanan, menyelesaikan penghantaran, dan memberikan sokongan pelanggan.",
      "- Data peribadi yang kami kendalikan: nama, nombor telefon, alamat penghantaran, e-mel (pilihan), dan imej resit pembayaran.",
      "- Kami tidak memindahkan data peribadi anda ke luar Malaysia kecuali kepada rakan kurier yang diperlukan untuk menghantar bungkusan anda.",
      "- Anda berhak mengakses, membetulkan, atau memohon pemadaman data peribadi anda pada bila-bila masa dengan menghubungi kami menggunakan butiran di halaman Hubungi Kami.",
      "- Kami menyimpan rekod pesanan sehingga 7 tahun untuk tujuan perakaunan dan cukai, seperti yang lazimnya dikehendaki oleh undang-undang Malaysia.",
      "",
      "Polisi ini mungkin dikemas kini dari semasa ke semasa. Versi terkini sentiasa terpakai.",
    ].join("\n"),
  },
};

export const termsAndConditionsDefault: StorefrontPage = {
  key: "terms_and_conditions",
  title: "Terms and Conditions",
  isActive: true,
  sortOrder: 100,
  localizedTitle: {
    en: "Terms and Conditions",
    zh: "条款与条件",
    ms: "Terma dan Syarat",
  },
  content: [
    "By placing an order at Urbanix Store, you agree to the following terms.",
    "",
    "- Orders are confirmed only after the payment receipt is verified by our team.",
    "- Product images are for reference; actual colors may vary slightly due to lighting and display settings.",
    "- Prices, promotions, and stock may change without prior notice.",
    "- We may cancel and refund any order in cases of suspected fraud or pricing errors.",
    "- These terms are governed by the laws of Malaysia.",
    "",
    "For any question, contact us via WhatsApp or email using the details in the footer.",
  ].join("\n"),
  localizedContent: {
    en: [
      "By placing an order at Urbanix Store, you agree to the following terms.",
      "",
      "- Orders are confirmed only after the payment receipt is verified by our team.",
      "- Product images are for reference; actual colors may vary slightly due to lighting and display settings.",
      "- Prices, promotions, and stock may change without prior notice.",
      "- We may cancel and refund any order in cases of suspected fraud or pricing errors.",
      "- These terms are governed by the laws of Malaysia.",
      "",
      "For any question, contact us via WhatsApp or email using the details in the footer.",
    ].join("\n"),
    zh: [
      "在 Urbanix Store 下单即表示您同意以下条款。",
      "",
      "- 订单需在我们的团队核实付款凭证后才会确认。",
      "- 产品图片仅供参考，实物颜色可能因灯光与屏幕显示而略有不同。",
      "- 价格、促销与库存如有更改，恕不另行通知。",
      "- 如发现疑似欺诈或价格错误，我们可取消订单并退款。",
      "- 本条款受马来西亚法律管辖。",
      "",
      "如有任何疑问，请通过页脚显示的 WhatsApp 或电邮联系我们。",
    ].join("\n"),
    ms: [
      "Dengan membuat pesanan di Urbanix Store, anda bersetuju dengan terma berikut.",
      "",
      "- Pesanan disahkan hanya selepas resit pembayaran disahkan oleh pasukan kami.",
      "- Gambar produk adalah untuk rujukan; warna sebenar mungkin berbeza sedikit kerana cahaya dan tetapan paparan.",
      "- Harga, promosi dan stok boleh berubah tanpa notis terlebih dahulu.",
      "- Kami boleh membatalkan dan memulangkan wang bagi mana-mana pesanan yang disyaki penipuan atau ralat harga.",
      "- Terma ini tertakluk kepada undang-undang Malaysia.",
      "",
      "Untuk sebarang pertanyaan, hubungi kami melalui WhatsApp atau e-mel menggunakan butiran di footer.",
    ].join("\n"),
  },
};

export const refundPolicyDefault: StorefrontPage = {
  key: "refund_policy",
  title: "Refund Policy",
  isActive: true,
  sortOrder: 101,
  localizedTitle: {
    en: "Refund Policy",
    zh: "退款政策",
    ms: "Polisi Bayaran Balik",
  },
  content: [
    "Once your return is received and inspected, we will WhatsApp or email you to confirm.",
    "",
    "- Refunds are processed within 5 working days via the same method you used to pay (bank transfer / e-wallet).",
    "- Refunds cover the item price. Original shipping is non-refundable unless the return is due to our error.",
    "",
    "**If your refund has not arrived in 5 working days**",
    "1. Check your bank statement.",
    "2. Contact your bank — refunds can take additional time to post.",
    "3. If still not received, WhatsApp us with your order number and we will trace it with you.",
  ].join("\n"),
  localizedContent: {
    en: [
      "Once your return is received and inspected, we will WhatsApp or email you to confirm.",
      "",
      "- Refunds are processed within 5 working days via the same method you used to pay (bank transfer / e-wallet).",
      "- Refunds cover the item price. Original shipping is non-refundable unless the return is due to our error.",
      "",
      "**If your refund has not arrived in 5 working days**",
      "1. Check your bank statement.",
      "2. Contact your bank — refunds can take additional time to post.",
      "3. If still not received, WhatsApp us with your order number and we will trace it with you.",
    ].join("\n"),
    zh: [
      "我们收到并检查您退回的商品后，会通过 WhatsApp 或电邮通知您。",
      "",
      "- 退款将于 5 个工作日内按原付款方式（银行转账 / 电子钱包）退回。",
      "- 退款金额为商品售价。原运费不予退还，除非是本店出错。",
      "",
      "**若 5 个工作日内仍未收到退款**",
      "1. 请检查银行月结单。",
      "2. 联系您的银行——退款可能需要额外处理时间。",
      "3. 若仍未收到，请 WhatsApp 我们订单编号，我们将协助追查。",
    ].join("\n"),
    ms: [
      "Setelah pemulangan anda diterima dan diperiksa, kami akan WhatsApp atau e-mel anda untuk pengesahan.",
      "",
      "- Bayaran balik akan diproses dalam 5 hari bekerja melalui kaedah yang sama dengan pembayaran anda (pemindahan bank / e-wallet).",
      "- Bayaran balik merangkumi harga barang. Caj penghantaran asal tidak dipulangkan kecuali pemulangan disebabkan oleh kesilapan kami.",
      "",
      "**Jika bayaran balik belum tiba dalam 5 hari bekerja**",
      "1. Semak penyata bank anda.",
      "2. Hubungi bank anda — bayaran balik mungkin mengambil masa tambahan untuk diposkan.",
      "3. Jika masih belum diterima, WhatsApp kami dengan nombor pesanan anda dan kami akan membantu mengesannya.",
    ].join("\n"),
  },
};

export const returnPolicyDefault: StorefrontPage = {
  key: "return_policy",
  title: "Return Policy",
  isActive: true,
  sortOrder: 102,
  localizedTitle: {
    en: "Return Policy",
    zh: "退换货政策",
    ms: "Polisi Pemulangan",
  },
  content: [
    "We accept returns for unopened items within 7 days of delivery for the following reasons:",
    "",
    "- Wrong item received — we cover return shipping.",
    "- Manufacturer defect — we cover return shipping.",
    "- Changed your mind — you cover return shipping.",
    "",
    "**How to return**",
    "1. WhatsApp us your order number and the reason within 7 days of receiving the parcel.",
    "2. We reply with the return address and instructions.",
    "3. Pack the item in its original box with all accessories.",
    "4. Use a tracked courier (Pos Laju / J&T / Ninja) and send us the tracking number.",
    "5. After we receive and inspect the item (1–2 working days), we process your refund or replacement.",
    "",
    "**We cannot accept returns for**",
    "- Items used or with damaged packaging (unless faulty).",
    "- Items returned beyond 7 days.",
    "- Promotional items marked \"final sale\".",
    "",
    "**Damaged or wrong item on arrival**",
    "1. Take clear photos of the damage and the outer packaging within 24 hours of receiving the parcel.",
    "2. WhatsApp us the photos and your order number.",
    "3. We reply within 24 hours with a replacement (shipped within 1–2 working days) or a full refund. There is no cost to you.",
  ].join("\n"),
  localizedContent: {
    en: [
      "We accept returns for unopened items within 7 days of delivery for the following reasons:",
      "",
      "- Wrong item received — we cover return shipping.",
      "- Manufacturer defect — we cover return shipping.",
      "- Changed your mind — you cover return shipping.",
      "",
      "**How to return**",
      "1. WhatsApp us your order number and the reason within 7 days of receiving the parcel.",
      "2. We reply with the return address and instructions.",
      "3. Pack the item in its original box with all accessories.",
      "4. Use a tracked courier (Pos Laju / J&T / Ninja) and send us the tracking number.",
      "5. After we receive and inspect the item (1–2 working days), we process your refund or replacement.",
      "",
      "**We cannot accept returns for**",
      "- Items used or with damaged packaging (unless faulty).",
      "- Items returned beyond 7 days.",
      "- Promotional items marked \"final sale\".",
      "",
      "**Damaged or wrong item on arrival**",
      "1. Take clear photos of the damage and the outer packaging within 24 hours of receiving the parcel.",
      "2. WhatsApp us the photos and your order number.",
      "3. We reply within 24 hours with a replacement (shipped within 1–2 working days) or a full refund. There is no cost to you.",
    ].join("\n"),
    zh: [
      "下列情况我们接受 7 天内未拆封商品退货：",
      "",
      "- 收到错误商品 —— 退货运费由我们承担。",
      "- 出厂瑕疵 —— 退货运费由我们承担。",
      "- 改变主意 —— 退货运费由您承担。",
      "",
      "**退货流程**",
      "1. 收到包裹 7 天内 WhatsApp 我们提供订单编号及原因。",
      "2. 我们会回复退货地址及说明。",
      "3. 将商品连同所有配件装回原包装。",
      "4. 使用有追踪号的快递（Pos Laju / J&T / Ninja）寄出，并将追踪号告知我们。",
      "5. 我们收件并检查后（1–2 个工作日），将办理退款或换货。",
      "",
      "**下列情况无法接受退货**",
      "- 已使用或包装损坏的商品（除非瑕疵）。",
      "- 超过 7 天的退货申请。",
      "- 标示「final sale」的促销商品。",
      "",
      "**收到损坏或错送商品**",
      "1. 请于收货 24 小时内拍下损坏部位及外包装的清晰照片。",
      "2. 将照片及订单编号 WhatsApp 给我们。",
      "3. 我们 24 小时内回复处理方案——补寄（1–2 个工作日内发货）或全额退款。您无需承担任何费用。",
    ].join("\n"),
    ms: [
      "Kami menerima pemulangan untuk barang yang belum dibuka dalam tempoh 7 hari selepas penerimaan untuk sebab berikut:",
      "",
      "- Salah barang diterima — kami menanggung kos pos pulangan.",
      "- Kecacatan pengeluaran — kami menanggung kos pos pulangan.",
      "- Berubah fikiran — anda menanggung kos pos pulangan.",
      "",
      "**Cara memulangkan**",
      "1. WhatsApp kami nombor pesanan dan sebab anda dalam 7 hari selepas menerima bungkusan.",
      "2. Kami akan balas dengan alamat pemulangan dan arahan.",
      "3. Bungkus barang di dalam kotak asal beserta semua aksesori.",
      "4. Gunakan kurier dengan penjejakan (Pos Laju / J&T / Ninja) dan beri kami nombor penjejakan.",
      "5. Selepas kami menerima dan memeriksa barang (1–2 hari bekerja), kami akan memproses bayaran balik atau penggantian anda.",
      "",
      "**Kami tidak menerima pemulangan untuk**",
      "- Barang yang telah digunakan atau pembungkusan rosak (kecuali rosak).",
      "- Pemulangan selepas 7 hari.",
      "- Barang promosi yang ditanda \"final sale\".",
      "",
      "**Barang rosak atau salah hantar semasa diterima**",
      "1. Ambil gambar jelas kerosakan dan pembungkusan luar dalam masa 24 jam selepas menerima bungkusan.",
      "2. WhatsApp kami gambar dan nombor pesanan anda.",
      "3. Kami akan membalas dalam masa 24 jam dengan penggantian (dihantar dalam 1–2 hari bekerja) atau bayaran balik penuh. Anda tidak perlu mengeluarkan sebarang kos.",
    ].join("\n"),
  },
};

export const faqDefault: StorefrontPage = {
  key: "faq",
  title: "Frequently Asked Questions",
  isActive: true,
  sortOrder: 103,
  localizedTitle: {
    en: "Frequently Asked Questions",
    zh: "常见问题",
    ms: "Soalan Lazim",
  },
  content: [
    "**1. How do I place an order?**",
    "Add items to your cart, go to checkout, fill in your details, choose QR payment, transfer the exact amount, upload your receipt, then tap Place Order. An order confirmation appears immediately.",
    "",
    "**2. What payment methods do you accept?**",
    "Bank QR / DuitNow QR. You can transfer from any Malaysian bank app or e-wallet (Maybank, CIMB, Public Bank, TnG, Boost, GrabPay, and others).",
    "",
    "**3. How long until you ship my order?**",
    "We verify payment within 24 hours, then pack and ship within 1–2 working days. The tracking number is sent via WhatsApp.",
    "",
    "**4. How long is delivery?**",
    "West Malaysia 2–4 working days. East Malaysia (Sabah / Sarawak / Labuan) 4–7 working days. Couriers: J&T, Ninja Van, Pos Laju.",
    "",
    "**5. Do you offer free shipping?**",
    "Yes — free shipping for West Malaysia orders above RM80 and East Malaysia orders above RM150.",
    "",
    "**6. I transferred the wrong amount, what should I do?**",
    "WhatsApp us your order number and a screenshot of your actual transfer within 24 hours. We will either share top-up instructions or refund the difference.",
    "",
    "**7. My receipt upload failed, what do I do?**",
    "WhatsApp us your receipt photo, name, phone number, and the items you want to order. We will create the order for you manually.",
    "",
    "**8. Can I change my delivery address?**",
    "Only before we ship (within 24 hours of payment verification). WhatsApp us as soon as possible with your order number and new address.",
    "",
    "**9. How do I track my order?**",
    "Go to Track Order in the menu and enter your order number and phone number. You can also use the tracking link we send via WhatsApp.",
    "",
    "**10. I received a damaged item. What now?**",
    "WhatsApp us clear photos and your order number within 24 hours of delivery. We will arrange a replacement or refund at no extra cost to you.",
  ].join("\n"),
  localizedContent: {
    en: [
      "**1. How do I place an order?**",
      "Add items to your cart, go to checkout, fill in your details, choose QR payment, transfer the exact amount, upload your receipt, then tap Place Order. An order confirmation appears immediately.",
      "",
      "**2. What payment methods do you accept?**",
      "Bank QR / DuitNow QR. You can transfer from any Malaysian bank app or e-wallet (Maybank, CIMB, Public Bank, TnG, Boost, GrabPay, and others).",
      "",
      "**3. How long until you ship my order?**",
      "We verify payment within 24 hours, then pack and ship within 1–2 working days. The tracking number is sent via WhatsApp.",
      "",
      "**4. How long is delivery?**",
      "West Malaysia 2–4 working days. East Malaysia (Sabah / Sarawak / Labuan) 4–7 working days. Couriers: J&T, Ninja Van, Pos Laju.",
      "",
      "**5. Do you offer free shipping?**",
      "Yes — free shipping for West Malaysia orders above RM80 and East Malaysia orders above RM150.",
      "",
      "**6. I transferred the wrong amount, what should I do?**",
      "WhatsApp us your order number and a screenshot of your actual transfer within 24 hours. We will either share top-up instructions or refund the difference.",
      "",
      "**7. My receipt upload failed, what do I do?**",
      "WhatsApp us your receipt photo, name, phone number, and the items you want to order. We will create the order for you manually.",
      "",
      "**8. Can I change my delivery address?**",
      "Only before we ship (within 24 hours of payment verification). WhatsApp us as soon as possible with your order number and new address.",
      "",
      "**9. How do I track my order?**",
      "Go to Track Order in the menu and enter your order number and phone number. You can also use the tracking link we send via WhatsApp.",
      "",
      "**10. I received a damaged item. What now?**",
      "WhatsApp us clear photos and your order number within 24 hours of delivery. We will arrange a replacement or refund at no extra cost to you.",
    ].join("\n"),
    zh: [
      "**1. 如何下单？**",
      "加入购物车 → 前往结账 → 填写资料 → 选择 QR 付款 → 按所示金额准确转账 → 上传付款收据 → 提交订单。提交后会立即显示订单确认。",
      "",
      "**2. 接受哪些付款方式？**",
      "银行 QR / DuitNow QR。可使用任何马来西亚银行 App 或电子钱包（Maybank、CIMB、Public Bank、TnG、Boost、GrabPay 等）转账。",
      "",
      "**3. 多久后会发货？**",
      "24 小时内核实付款，之后 1–2 个工作日内打包发货。追踪号码通过 WhatsApp 发送。",
      "",
      "**4. 配送需要多久？**",
      "西马 2–4 个工作日，东马（沙巴 / 砂拉越 / 纳闽）4–7 个工作日。快递：J&T、Ninja Van、Pos Laju。",
      "",
      "**5. 有免运吗？**",
      "有的——西马订单满 RM80、东马订单满 RM150 免邮费。",
      "",
      "**6. 我转账金额错了怎么办？**",
      "请于 24 小时内 WhatsApp 我们订单编号及实际转账截图，我们会安排补差额或退还差额。",
      "",
      "**7. 收据上传失败怎么办？**",
      "请将收据照片、姓名、电话及想买的商品 WhatsApp 给我们，我们会代您下单。",
      "",
      "**8. 可以更改收货地址吗？**",
      "仅限发货前（付款核实后 24 小时内）。请尽快 WhatsApp 我们订单编号及新地址。",
      "",
      "**9. 如何追踪订单？**",
      "进入选单中的「追踪订单」，输入订单编号及电话号码即可。也可使用我们 WhatsApp 中的追踪链接。",
      "",
      "**10. 收到损坏商品怎么办？**",
      "请于收货 24 小时内 WhatsApp 我们提供清晰照片及订单编号，我们将免费换货或退款。",
    ].join("\n"),
    ms: [
      "**1. Bagaimana saya membuat pesanan?**",
      "Tambah ke troli → ke pembayaran → isi maklumat → pilih bayaran QR → pindahkan jumlah tepat → muat naik resit → tekan Buat Pesanan. Pengesahan pesanan akan dipaparkan serta-merta.",
      "",
      "**2. Apakah kaedah pembayaran yang anda terima?**",
      "QR Bank / QR DuitNow. Pindah dari mana-mana aplikasi bank Malaysia atau e-wallet (Maybank, CIMB, Public Bank, TnG, Boost, GrabPay, dan lain-lain).",
      "",
      "**3. Berapa lama sebelum pesanan saya dihantar?**",
      "Kami sahkan bayaran dalam 24 jam, kemudian bungkus dan hantar dalam 1–2 hari bekerja. Nombor penjejakan dihantar melalui WhatsApp.",
      "",
      "**4. Berapa lama penghantaran?**",
      "Semenanjung Malaysia 2–4 hari bekerja. Malaysia Timur (Sabah / Sarawak / Labuan) 4–7 hari bekerja. Kurier: J&T, Ninja Van, Pos Laju.",
      "",
      "**5. Adakah penghantaran percuma?**",
      "Ya — penghantaran percuma untuk pesanan Semenanjung Malaysia melebihi RM80 dan pesanan Malaysia Timur melebihi RM150.",
      "",
      "**6. Saya pindahkan jumlah yang salah, apa patut saya buat?**",
      "WhatsApp kami nombor pesanan dan tangkapan skrin pindahan sebenar dalam 24 jam. Kami akan beri arahan tambah bayaran atau pulangkan perbezaan.",
      "",
      "**7. Muat naik resit saya gagal, apa patut saya buat?**",
      "WhatsApp kami gambar resit, nama, nombor telefon, dan barang yang ingin dibeli. Kami akan membuat pesanan secara manual untuk anda.",
      "",
      "**8. Bolehkah saya tukar alamat penghantaran?**",
      "Hanya sebelum kami menghantar (dalam 24 jam selepas pengesahan bayaran). WhatsApp kami secepat mungkin dengan nombor pesanan dan alamat baru.",
      "",
      "**9. Bagaimana saya menjejak pesanan?**",
      "Ke Jejak Pesanan di menu, masukkan nombor pesanan dan telefon. Anda juga boleh guna pautan penjejakan yang kami hantar melalui WhatsApp.",
      "",
      "**10. Saya terima barang yang rosak. Apa sekarang?**",
      "WhatsApp kami gambar jelas dan nombor pesanan dalam 24 jam selepas penerimaan. Kami akan ganti atau pulangkan wang — tanpa kos tambahan.",
    ].join("\n"),
  },
};
